version: '3.3'
 
services:
  client:
      build: .
      ports:
        - '4200'
        - '49153:49153'
      volumes:
        - .:/usr/src/app/
  nginx:
    build: ./.nginx
    ports:
      - "80:80"
    links:
      - client